# Generated by Django 4.1.7 on 2023-02-28 10:11

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


def copy_data(apps, schema_editor):
    call_command("move_sales")


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_selling_order_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selling",
            name="product",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.product",
            ),
        ),
        migrations.RunPython(copy_data, migrations.RunPython.noop),
        migrations.RunSQL(
            """
            SELECT setval('main_selling_id_seq', max(id)) FROM main_selling;
            """,
            migrations.RunSQL.noop,
        ),
    ]
