# Generated by Django 4.1.7 on 2023-02-28 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_MOVE_SALES"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selling",
            name="dt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
